// demos/react-host/src/App.tsx
import { useEffect, useRef, useState } from "react";

const DEFAULT_REMOTE_URL = "http://localhost:8081";

type EmbeddedModule = {
    render: (rootNode: Element | null, options: { remoteUrl: string; minHeight: string, parameters: Record<string, any> }) => Promise<() => void>;
};

const metrics = [
    { label: "Claims in queue", value: "148", change: "+12 today" },
    { label: "Automation rate", value: "86%", change: "+4.1% week-on-week" },
    { label: "Avg. handling time", value: "4m 12s", change: "-38s vs target" },
];

const activity = [
    "Regional claims import completed successfully.",
    "Underwriting portal synced customer documents 2 minutes ago.",
    "Embedded Mendix workspace ready for policy review.",
];

export default function App() {
    const hostRef = useRef<HTMLDivElement | null>(null);
    const moduleRef = useRef<EmbeddedModule | null>(null);
    const unmountRef = useRef<() => void>(() => undefined);
    const [status, setStatus] = useState("Loading embedded Mendix app...");
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        let isActive = true;

        const mountEmbeddedApp = async () => {
            const configuredRemoteUrl =
                (window as Window & { __MENDIX_REMOTE_URL__?: string }).__MENDIX_REMOTE_URL__ ?? DEFAULT_REMOTE_URL;
            const remoteUrl = configuredRemoteUrl.replace(/\/+$/, "");

            try {
                if (!moduleRef.current) {
                    moduleRef.current = (await import(`${remoteUrl}/dist/embedded-index.js`)) as EmbeddedModule;
                }

                if (!isActive) {
                    return;
                }

                document.body.setAttribute("data-demo-theme", "executive");

                unmountRef.current = await moduleRef.current.render(hostRef.current, {
                    remoteUrl: `${remoteUrl}/`,
                    minHeight: "620px",
                    parameters: {
                        Name: "React"
                    }
                });

                if (isActive) {
                    setStatus("Embedded Mendix app connected");
                    setError(null);
                }
            } catch (mountError) {
                console.error(mountError);
                if (isActive) {
                    setError(
                        `Unable to load the embedded Mendix bundle from ${remoteUrl}/dist/embedded-index.js.`
                    );
                    setStatus("Waiting for embedded Mendix runtime");
                }
            }
        };

        void mountEmbeddedApp();

        return () => {
            isActive = false;
            unmountRef.current();
        };
    }, []);

    return (
        <div className="page-shell">
            <aside className="sidebar">
                <div>
                    <p className="eyebrow">Northstar Mutual</p>
                    <h1>Operations Command</h1>
                    <p className="muted">A lightweight host shell around an embedded Mendix workspace.</p>
                </div>
                <nav className="nav-card">
                    <span className="nav-label nav-active">Claims workspace</span>
                    <span className="nav-label">Service requests</span>
                    <span className="nav-label">Broker onboarding</span>
                </nav>
                <section className="activity-card">
                    <h2>Live activity</h2>
                    {activity.map(item => (
                        <p key={item}>{item}</p>
                    ))}
                </section>
            </aside>

            <main className="content">
                <header className="hero-card">
                    <div>
                        <p className="eyebrow">Embedded Experience Demo</p>
                        <h2>Claims review dashboard</h2>
                        <p className="hero-copy lead mb-0">
                            This React app provides a realistic dashboard frame while the actual workflow is rendered by Mendix in embedded mode.
                        </p>
                    </div>
                    <div className="status-panel">
                        <span className="status-dot" />
                        <div>
                            <strong>{status}</strong>
                            <p className="small mb-0">Expected remote bundle: `{DEFAULT_REMOTE_URL}/dist/embedded-index.js`</p>
                        </div>
                    </div>
                </header>

                <section className="metrics-grid" aria-label="Operational metrics">
                    {metrics.map(metric => (
                        <article className="metric-card" key={metric.label}>
                            <p>{metric.label}</p>
                            <strong>{metric.value}</strong>
                            <span>{metric.change}</span>
                        </article>
                    ))}
                </section>

                <section className="workspace-card">
                    <div className="workspace-header">
                        <div>
                            <p className="eyebrow">Embedded app region</p>
                            <h3>Mendix workspace</h3>
                        </div>
                        <span className="badge rounded-pill text-bg-primary">Shadow DOM ready</span>
                    </div>

                    {error ? <div className="error-banner">{error}</div> : null}

                    <div className="embedded-stage">
                        <div ref={hostRef} className="embedded-host" data-testid="embedded-mendix-host" />
                    </div>
                </section>
            </main>
        </div>
    );
}

// demos/vue-host/src/App.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from "vue";

const DEFAULT_REMOTE_URL = "http://localhost:8081";

type EmbeddedModule = {
    render: (rootNode: Element | null, options: { remoteUrl: string; minHeight: string }) => Promise<() => void>;
};

const pipelineSteps = ["Intake captured", "Eligibility scored", "Manual review embedded"];

const briefingCards = [
    { label: "Partner submissions", value: "54", detail: "11 require intervention" },
    { label: "Straight-through rate", value: "73%", detail: "+6 points this quarter" },
    { label: "SLA health", value: "98.2%", detail: "Within partner promise" },
];

const status = ref("Loading embedded Mendix app...");
const error = ref<string | null>(null);
const embeddedHost = ref<HTMLDivElement | null>(null);
const embeddedModule = ref<EmbeddedModule | null>(null);
let unmountEmbeddedApp: () => void = () => undefined;

onMounted(async () => {
    const configuredRemoteUrl = (window as Window & { __MENDIX_REMOTE_URL__?: string }).__MENDIX_REMOTE_URL__;
    const remoteUrl = (configuredRemoteUrl ?? DEFAULT_REMOTE_URL).replace(/\/+$/, "");

    try {
        if (!embeddedModule.value) {
            embeddedModule.value = (await import(/* @vite-ignore */ `${remoteUrl}/dist/embedded-index.js`)) as EmbeddedModule;
        }

        document.body.setAttribute("data-demo-theme", "partner-workspace");

        unmountEmbeddedApp = await embeddedModule.value.render(embeddedHost.value, {
            remoteUrl: `${remoteUrl}/`,
            minHeight: "640px",
            parameters: {
                Name: "Vue"
            }
        });

        status.value = "Embedded Mendix app connected";
        error.value = null;
    } catch (mountError) {
        console.error(mountError);
        status.value = "Waiting for embedded Mendix runtime";
        error.value = `Unable to load the embedded Mendix bundle from ${remoteUrl}/dist/embedded-index.js.`;
    }
});

onBeforeUnmount(() => {
    unmountEmbeddedApp();
});
</script>

<template>
    <div class="workspace-shell">
        <header class="topbar">
            <div>
                <p class="eyebrow">Harbor Partner Platform</p>
                <h1>Distribution Workspace</h1>
                <p class="lede">
                    A Vue-based host shell showing how Mendix can power one embedded operational journey inside a broader partner experience.
                </p>
            </div>
            <div class="runtime-chip">
                <span class="runtime-pulse"></span>
                <div>
                    <strong>{{ status }}</strong>
                    <p>Mendix runtime expected on `http://localhost:8081`</p>
                </div>
            </div>
        </header>

        <section class="hero-grid">
            <aside class="signal-rail">
                <div class="signal-card">
                    <p class="eyebrow">Why this matters</p>
                    <h2>One portal, multiple delivery models</h2>
                    <p>
                        The surrounding shell stays in Vue while Mendix delivers the embedded workflow where speed and iteration matter most.
                    </p>
                </div>

                <div class="signal-card">
                    <p class="eyebrow">Journey stages</p>
                    <ul class="pipeline-list">
                        <li v-for="step in pipelineSteps" :key="step">{{ step }}</li>
                    </ul>
                </div>
            </aside>

            <main class="main-column">
                <section class="briefing-grid" aria-label="Partner operations metrics">
                    <article v-for="card in briefingCards" :key="card.label" class="briefing-card">
                        <p>{{ card.label }}</p>
                        <strong>{{ card.value }}</strong>
                        <span>{{ card.detail }}</span>
                    </article>
                </section>

                <section class="embed-card">
                    <div class="embed-header">
                        <div>
                            <p class="eyebrow">Embedded workspace</p>
                            <h2>Mendix submission review flow</h2>
                        </div>
                        <span class="badge rounded-pill text-bg-light">Host on :3000</span>
                    </div>

                    <p class="embed-copy">
                        This area is where the Mendix experience appears inside the Vue portal shell. It is the part of the demo that should draw attention during a customer conversation.
                    </p>

                    <div v-if="error" class="alert alert-danger mb-3" role="alert">{{ error }}</div>

                    <div class="embedded-frame">
                        <div ref="embeddedHost" class="embedded-surface" data-testid="embedded-mendix-host"></div>
                    </div>
                </section>
            </main>
        </section>
    </div>
</template>
